replicaCount: 1

image:
  repository: porcupine.azurecr.io/porc
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-creds

mongo:
  uri: "mongodb://porcmongo.mongocluster.cosmos.azure.com:27017/porc"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  enabled: false