replicaCount: 1

image:
  repository: porcupine.azurecr.io/porc
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-creds

mongo:
  uri: "mongodb://porcmongo.mongocluster.cosmos.azure.com:27017/porc"

tfeTokenSecretName: tfe-secrets

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: porc.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: porc-tls
      hosts:
        - porc.example.com
