⁷replicaCount: 1

image:
  repository: porcupine.azurecr.io/porc
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-creds

# MongoDB connection string is now provided via the 'mongo-secrets' Kubernetes secret
# mongo:
#   uri: "mongodb+srv://porcupine:<password>@porcmongo.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"

tfeTokenSecretName: tfe-secrets

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: porc.example.com
      paths:
        - path: /
          pathType: Prefix
