apiVersion: v1
kind: ConfigMap
metadata:
  name: github-app-config
  namespace: default
data:
  GITHUB_APP_ID: "${GITHUB_APP_ID}"
  GITHUB_APP_INSTALLATION_ID: "${GITHUB_APP_INSTALLATION_ID}"
  GITHUB_APP_PRIVATE_KEY: "${GITHUB_APP_PRIVATE_KEY}"
  GITHUB_APP_TYPE: "app"  # This tells PORC to use GitHub App auth instead of PAT 