replicaCount: 1

image:
  repository: porcupine.azurecr.io/porc
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-creds

mongo:
  uri: "mongodb://porcmongo.mongocluster.cosmos.azure.com:27017/porc"

env:
  TFE_TOKEN: ""
  TFE_HOST: "https://app.terraform.io/api/v2"
  TFE_ORG: "td-organization"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi