apiVersion: apps/v1
kind: Deployment
metadata:
  name: porc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: porc
  template:
    metadata:
      labels:
        app: porc
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: porc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_URI
            - name: TFE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tfe.tokenSecretName }}
                  key: TFE_TOKEN
            - name: TFE_HOST
              value: {{ .Values.tfe.host | quote }}
            - name: TFE_ORG
              value: {{ .Values.tfe.org | quote }}
            - name: TFE_ENV
              value: {{ .Values.tfe.env | quote }}
            - name: GITHUB_REPOSITORY
              value: {{ .Values.github.repository | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
