apiVersion: apps/v1
kind: Deployment
metadata:
  name: porc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: porc
  template:
    metadata:
      labels:
        app: porc
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: porc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "{{ .Values.mongo.uri }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}