apiVersion: v1
kind: Service
metadata:
  name: porc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: porc
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}