name: Lint

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install linting & formatting tools
        run: |
          pip install flake8 ruff autopep8 autoflake isort

      - name: Remove unused imports & variables
        run: |
          autoflake --remove-all-unused-imports --remove-unused-variables \
            --recursive --in-place .

      - name: Sort imports
        run: |
          isort .

      - name: Auto-format code
        run: |
          autopep8 --in-place --aggressive --aggressive --recursive .

      - name: Apply Ruff fixes
        run: |
          ruff fix .

      - name: Run Flake8
        run: |
          flake8 . --ignore=E501,W503
