name: PORC API Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL for the PORC API'
        required: false
        default: 'https://172.212.51.168/'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run tests
        run: |
          pytest test/ --base-url=${{ github.event.inputs.base_url || 'https://172.212.51.168/' }} --pr-id ${{ github.event.number }} --pr-sha ${{ github.sha }} --ignore-ssl
        env:
          PR_ID: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
