name: PORC API Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run tests
        run: |
          pytest porc/tests/ --pr-id ${{ github.event.number }} --pr-sha ${{ github.sha }}
        env:
          PR_ID: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
