name: Sync Documentation to Wiki

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'pine/docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'
      - 'DOCUMENTATION.md'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Clone wiki repo
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Copy docs into wiki
        run: |
          cp README.md wiki/Home.md
          cp CONTRIBUTING.md wiki/
          cp CHANGELOG.md wiki/
          cp DOCUMENTATION.md wiki/
          cp docs/architecture.md wiki/Architecture.md
          cp pine/docs/usage.md wiki/PINE-Usage.md
          cp logo.png wiki/logo.png

      - name: Commit and push to wiki
        run: |
          cd wiki
          git add .
          git commit -m "Sync docs to wiki [automated]" || echo "No changes to commit"
          git push