name: Sync Wiki

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/wiki-sync.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone wiki repo using GITHUB_TOKEN
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Copy updated docs into wiki
        run: |
          rsync -av --delete --exclude='.DS_Store' --exclude='.git' docs/ wiki/

      - name: Commit and push to wiki
        run: |
          cd wiki
          git add .
          git commit -m "Sync from docs at ${{ github.sha }} by ${{ github.actor }}" || echo "Nothing to commit"
          git push